language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install requests
  - pip install codecov

script:
  - python setup.py install
  - pytest -v
  - coverage run test_vtapi3.py
  - coverage run test_vtapi3_main.py

after_success:
  - codecov