environment:
  matrix:
    - PYTHON: "C:\\Python34"
    - PYTHON: "C:\\Python34-x64"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python35-x64"
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python36-x64"
    - PYTHON: "C:\\Python37"
    - PYTHON: "C:\\Python37-x64"
    - PYTHON: "C:\\Python38"
    - PYTHON: "C:\\Python38-x64"
install:
  - cmd: "C:\\Python37\\python.exe -m pip install requests"
build_script:
  - cmd: "C:\\Python37\\python.exe setup.py build"
test_script:
  - cmd: "C:\\Python37\\python.exe setup.py test"